#data path
data_path: '../data/'

#model path
model_path: '../data/model/'

#benchmark path
benchmark_path: '../data/TimeQuestions/'

#question seed entities and KG facts path
ques_path: '../data/files/'

#connect path file of seed pair
connect_path: '../data/connectivity/'

#compact subgraph path
compactsubg_path: '../data/compactgst/'

#compact subgraph with temporal facts path
temcompactsubg_path: '../data/temcompactgst/'

#relational graphs, dictionaries and pretrained embedding files path
answer_predict_path: '../data/dictionaries/'

#benchmark file
train_data: 'train.json'
dev_data: 'dev.json'
test_data: 'test.json'

#property file
property_file: 'wikidata_property_dictionary.json'

#Wikipedia2Vec model
wikipedia2vec: 'wikipedia2vec_trained'

#Default number of Facts to be considered 
top_f: 25

#Default number of GSTs to be considered
top_g: 25

#Default number of Temporal facts to be considered
top_t: 25
